name: 'Push Actions'
on: 
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v3
      -
         name: Set up Python
         uses: actions/setup-python@v3
         with:
           python-version: '3.8'
      - 
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - 
        name: Build package
        run: python -m build
      -
        name: Run Tests
        run: |
          python -m pip install pytest
          python -m pip install -r requirements.txt
          pytest --token ${{ secrets.KEBOOLA_TEST_TOKEN }}
      -
        name: Set tag
        id: tag
        run: |
          TAG="${GITHUB_REF##*/}"
          IS_SEMANTIC_TAG=$(echo "$TAG" | grep -q '^v\?[0-9]\+\.[0-9]\+\.[0-9]\+$' && echo true || echo false)
          echo "Tag = '$TAG', is semantic tag = '$IS_SEMANTIC_TAG'"
          echo "is_semantic_tag=$IS_SEMANTIC_TAG" >> $GITHUB_OUTPUT
          echo "app_image_tag=$TAG" >> $GITHUB_OUTPUT
      -
        name: deploy
        if: 'startsWith(github.ref, ''refs/tags/'') && ${{ steps.tag.outputs.is_semantic_tag }} == ''true'''
        run: |
          twine upload dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN }}
