name: 'Push Actions'
on: 
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v3
      -
         name: Set up Python
         uses: actions/setup-python@v3
         with:
           python-version: '3.10'
      - 
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - 
        name: Build package
        run: python -m build
      -
        name: Run Tests
        run: |
          python -m pip install pytest
          python -m pip install -r requirements.txt
          pytest --token ${{ secrets.KEBOOLA_TEST_TOKEN }}
        
